---
abstract: 'Bindings for Bitbucket Server REST APIs'
author:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  HTTP::AnyUA::Backend: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-BitbucketServer
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  WebService::BitbucketServer:
    file: lib/WebService/BitbucketServer.pm
    version: '0.604'
  WebService::BitbucketServer::AccessTokens::V1:
    file: lib/WebService/BitbucketServer/AccessTokens/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Audit::V1:
    file: lib/WebService/BitbucketServer/Audit/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Branch::V1:
    file: lib/WebService/BitbucketServer/Branch/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Build::V1:
    file: lib/WebService/BitbucketServer/Build/V1.pm
    version: '0.604'
  WebService::BitbucketServer::CommentLikes::V1:
    file: lib/WebService/BitbucketServer/CommentLikes/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Core::V1:
    file: lib/WebService/BitbucketServer/Core/V1.pm
    version: '0.604'
  WebService::BitbucketServer::DefaultReviewers::V1:
    file: lib/WebService/BitbucketServer/DefaultReviewers/V1.pm
    version: '0.604'
  WebService::BitbucketServer::GPG::V1:
    file: lib/WebService/BitbucketServer/GPG/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Git::V1:
    file: lib/WebService/BitbucketServer/Git/V1.pm
    version: '0.604'
  WebService::BitbucketServer::JIRA::V1:
    file: lib/WebService/BitbucketServer/JIRA/V1.pm
    version: '0.604'
  WebService::BitbucketServer::MirroringUpstream::V1:
    file: lib/WebService/BitbucketServer/MirroringUpstream/V1.pm
    version: '0.604'
  WebService::BitbucketServer::RefRestriction::V2:
    file: lib/WebService/BitbucketServer/RefRestriction/V2.pm
    version: '0.604'
  WebService::BitbucketServer::RepositoryRefSync::V1:
    file: lib/WebService/BitbucketServer/RepositoryRefSync/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Response:
    file: lib/WebService/BitbucketServer/Response.pm
    version: '0.604'
  WebService::BitbucketServer::SSH::V1:
    file: lib/WebService/BitbucketServer/SSH/V1.pm
    version: '0.604'
  WebService::BitbucketServer::Spec:
    file: lib/WebService/BitbucketServer/Spec.pm
    version: '0.604'
  WebService::BitbucketServer::WADL:
    file: lib/WebService/BitbucketServer/WADL.pm
    version: '0.604'
requires:
  Carp: '0'
  Clone: '0'
  Exporter: '0'
  HTTP::AnyUA: '0'
  HTTP::AnyUA::Util: '0'
  JSON: '0'
  MIME::Base64: '0'
  Module::Load: '0'
  Moo: '0'
  Scalar::Util: '0'
  Types::Standard: '0'
  namespace::clean: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/WebService-BitbucketServer/issues
  homepage: https://github.com/chazmcgarvey/WebService-BitbucketServer
  repository: https://github.com/chazmcgarvey/WebService-BitbucketServer.git
version: '0.604'
x_authority: cpan:CCM
x_contributors:
  - 'Camspi <amarus18@hotmail.com>'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.70'
